import re

def full_country_name(data):
    if not isinstance(data, str):
        return data 
    country_map = {
        'USA': 'United States',
        'EST': 'Estonia',
        'GBR': 'United Kingdom',
        'ARG': 'Argentina',
        'HKG': 'Hong Kong',
        'CHL': 'Chile',
        'DEU': 'Germany',
        'FRA': 'France',
        'CHN': 'China',
        'CAN': 'Canada',
        'AUS': 'Australia',
        'ROM': 'Romania',
        'NLD': 'Netherlands',
        'SWE': 'Sweden',
        'RUS': 'Russia',
        'DNK': 'Denmark',
        'IND': 'India',
        'SGP': 'Singapore',
        'NOR': 'Norway',
        'BEL': 'Belgium',
        'IRL': 'Ireland',
        'ITA': 'Italy',
        'ISR': 'Israel',
        'ESP': 'Spain',
        'THA': 'Thailand',
        'NZL': 'New Zealand',
        'CZE': 'Czech Republic',
        'CHE': 'Switzerland',
        'BRA': 'Brazil',
        'HUN': 'Hungary',
        'JPN': 'Japan',
        'BWA': 'Botswana',
        'KOR': 'South Korea',
        'NGA': 'Nigeria',
        'FIN': 'Finland',
        'TUR': 'Turkey',
        'CRI': 'Costa Rica',
        'PRT': 'Portugal',
        'TWN': 'Taiwan',
        'KHM': 'Cambodia',
        'COL': 'Colombia',
        'UKR': 'Ukraine',
        'LTU': 'Lithuania',
        'ZAF': 'South Africa',
        'AUT': 'Austria',
        'PHL': 'Philippines',
        'ISL': 'Iceland',
        'BGR': 'Bulgaria',
        'URY': 'Uruguay',
        'HRV': 'Croatia',
        'KEN': 'Kenya',
        'MEX': 'Mexico',
        'JOR': 'Jordan',
        'VNM': 'Vietnam',
        'GHA': 'Ghana',
        'PER': 'Peru',
        'POL': 'Poland',
        'IDN': 'Indonesia',
        'PAN': 'Panama',
        'LVA': 'Latvia',
        'ALB': 'Albania',
        'UGA': 'Uganda',
        'LBN': 'Lebanon',
        'GRC': 'Greece',
        'ARE': 'United Arab Emirates',
        'PAK': 'Pakistan',
        'EGY': 'Egypt',
        'SVK': 'Slovakia',
        'LUX': 'Luxembourg',
        'MYS': 'Malaysia',
        'BHS': 'Bahamas',
        'ARM': 'Armenia',
        'DZA': 'Algeria',
        'MDA': 'Moldova',
        'TUN': 'Tunisia',
        'NIC': 'Nicaragua',
        'TZA': 'Tanzania',
        'CYP': 'Cyprus',
        'NPL': 'Nepal',
        'BHR': 'Bahrain',
        'CMR': 'Cameroon',
        'SRB': 'Serbia',
        'SAU': 'Saudi Arabia',
        'CYM': 'Cayman Islands',
        'BRN': 'Brunei',
        'SLV': 'El Salvador',
        'ECU': 'Ecuador',
        'MLT': 'Malta',
        'SVN': 'Slovenia',
        'LAO': 'Laos',
        'TTO': 'Trinidad and Tobago',
        'MAR': 'Morocco',
        'MMR': 'Myanmar',
        'BGD': 'Bangladesh',
        'DOM': 'Dominican Republic',
        'BMU': 'Bermuda',
        'LIE': 'Liechtenstein',
        'MOZ': 'Mozambique',
        'GTM': 'Guatemala',
        'AZE': 'Azerbaijan',
        'MCO': 'Monaco',
        'ZWE': 'Zimbabwe',
        'UZB': 'Uzbekistan',
        'OMN': 'Oman',
        'BLR': 'Belarus',
        'JEY': 'Jersey',
        'JAM': 'Jamaica',
        'KWT': 'Kuwait',
        'MUS': 'Mauritius',
        'CIV': "Côte d’Ivoire",
        'SOM': 'Somalia',
        'MKD': 'North Macedonia',
        'GIB': 'Gibraltar',
        'SYC': 'Seychelles',
        'MAF': 'Saint Martin (French)'
    }

    for code, full in country_map.items():
        data = re.sub(rf'\b{code}\b', full, data)
    
    return data
