# -*- coding: utf-8 -*-
"""python_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PdllofZZ8fFf0679a74baD4wyAp5BBES

### `Problem-1:` Breaking the records.

Maria plays college basketball and wants to go pro. Each season she maintains a record of her play. She tabulates the number of times she breaks her season record for most points and least points in a game. Points scored in the first game establish her record for the season, and she begins counting from there.

**Example**

*scores = [12, 24, 10, 24]*

Scores are in the same order as the games played. She tabulates her results as follows:

| Game | Score | Minimum | Maximum | Count Min | Count Max |
| :--: | :--: | :--: | :--: | :--: | :--: |
| 0 | 12 | 12 | 12 | 0 | 0 |
| 1 | 24 | 12 | 24 | 0 | 1 |
| 2 | 10 | 10 | 24 | 1 | 1 |
| 3 | 24 | 10 | 24 | 1 | 1 |

Given the scores for a season, determine the number of times Maria breaks her records for most and least points scored during the season.

**Function Description**

Complete the breakingRecords function in the editor below.

breakingRecords has the following parameter(s):
- n: no of games
- int scores[n]: points scored per game

**Returns**

- int[2]: An array with the numbers of times she broke her records. Index 0 is for breaking most points records, and index 1 is for breaking least points records.

**Input Format**

n, the number of games.
Integers array osf scores describing the respective values of $score_0, score_1, score_2, ..., score_{n-1}$.

**Constraints**

- $1 <= n <= 1000$
- $0 <= scores[i] <= 10^8$

**Sample Input 0**

```bash
10 5 20 20 4 5 2 25 1
```

**Sample Output 0**

```bash
2 4
```

**Explanation 0**

The diagram below depicts the number of times Maria broke her best and worst records throughout the season:

| Games | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |
| :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: |
| **Score** | 10 | 5 | 20 | 20 | 4 | 5 | 2 | 25 | 1 |
| **Highest Score** | 10 | 10 | **20** | 20 | 20 | 20 | 20 | **25** | 25 |
| **Lowest Score** | 10 | **5** | 5 | 5 | **4** | 4 | **2** | 2 | **1** |

She broke her best record twice (after games 2 and 7) and her worst record four times (after games 1, 4, 6, and 8), so we print 2 4 as our answer. Note that she did not break her record for best score during game 3, as her score during that game was not strictly greater than her best record at the time.
"""

def breaking_records(n,arr):
    high_score = arr[0]
    low_score = arr[0]
    ans = [0,0]
    for i in range(1,n):
        if arr[i] > high_score:
            high_score = arr[i]
            ans[0]+=1
        elif arr[i] < low_score:
            low_score = arr[i]
            ans[1]+=1

    return ans
print(breaking_records(9,[10, 5, 20, 20, 4, 5, 2, 25, 1]))

"""### `Problem-2:` Student management system in Python

Write a program to build a simple Student Management System using Python which can perform the following operations:
1. **Accept -** This method takes details from the user like name, roll number, and marks for two different subjects.
2. **Display -** This method displays the details of every student.
3. **Search -** This method searches for a particular student from the list of students. This method will ask the user for roll number and then search according to the roll number
4. **Delete -** This method deletes the record of a particular student with a matching roll number.
5. **Update -**  This method updates the roll number of the student. This method will ask for the old roll number and new roll number. It will replace the old roll number with a new roll number.
"""

class Student:

    def __init__(self):
        self.name = None
        self.roll_no = None
        self.marks = None
        self.roll_no_data = []
        self.student_data = {}

    def accept(self,name,roll_no,marks):
        self.name = name
        self.roll_no = roll_no
        self.marks = marks
        self.roll_no_data.append(self.roll_no)
        self.student_data[roll_no] = [self.name,self.marks]


    def display(self):
        for i in self.student_data:
            print(f"Roll no: {i}\nName: {self.student_data[i][0]}\nMarks: {self.student_data[i][1]}")


    def search(self,roll_no):
        if roll_no in self.roll_no_data:
            return f"Name: {self.student_data[roll_no][0]}\nMarks: {self.student_data[roll_no][1]}"
        else:
            return f"Student Not found"

    def delete(self,roll_no):
        if roll_no in self.roll_no_data:
            self.roll_no_data.remove(roll_no)
            del self.student_data[roll_no]
            return f"Data Deleted Successfully"
        else:
            return f"Roll no not found"

    def update(self,old_rollno,new_rollno):
        if old_rollno in self.student_data:
            backup_data = self.student_data[old_rollno]
            old_student_name,old_student_marks = backup_data
            for i in range(len(self.roll_no_data)):
                if self.roll_no_data[i] == old_rollno:
                    self.roll_no_data[i] = new_rollno
            del self.student_data[old_rollno]
            self.student_data[new_rollno] = [old_student_name,old_student_marks]
            return f"Student Data Updated"
        else:
            return f"Student Roll no not present in data"

"""Problem-3: Get current times of different time zones in Python"""

from datetime import datetime
import pytz

pk_time = pytz.timezone('Asia/karachi')

print(datetime.now(pk_time))

"""# `Problem-4:` Python program to count Even and Odd numbers in a List using list comprehension.

Given a list of numbers, write a Python program to count Even and Odd numbers in a List.

**Example:**

```bash
Input: list1 = [2, 7, 5, 64, 14]
Output: Even = 3, odd = 2

Input: list2 = [12, 14, 95, 3]
Output: Even = 2, odd = 2
```
"""

list1 = [2, 7, 5, 64, 14]
even = lambda x : x if x%2==0 else 0
odd = lambda x : x if x%2!=0 else 0
Even_number_count = len(list(filter(even,list1)))
odd_number_count = len(list(filter(odd,list1)))
print(Even_number_count)
print(odd_number_count)

"""### `Problem-5:` Alphabet Rangoli

You are given an integer, $N$. Your task is to print an alphabet rangoli of size

$N$. (Rangoli is a form of Indian folk art based on creation of patterns.)

Different sizes of alphabet rangoli are shown below:

```bash
#size 3

----c----
--c-b-c--
c-b-a-b-c
--c-b-c--
----c----

#size 5

--------e--------
------e-d-e------
----e-d-c-d-e----
--e-d-c-b-c-d-e--
e-d-c-b-a-b-c-d-e
--e-d-c-b-c-d-e--
----e-d-c-d-e----
------e-d-e------
--------e--------

#size 10

------------------j------------------
----------------j-i-j----------------
--------------j-i-h-i-j--------------
------------j-i-h-g-h-i-j------------
----------j-i-h-g-f-g-h-i-j----------
--------j-i-h-g-f-e-f-g-h-i-j--------
------j-i-h-g-f-e-d-e-f-g-h-i-j------
----j-i-h-g-f-e-d-c-d-e-f-g-h-i-j----
--j-i-h-g-f-e-d-c-b-c-d-e-f-g-h-i-j--
j-i-h-g-f-e-d-c-b-a-b-c-d-e-f-g-h-i-j
--j-i-h-g-f-e-d-c-b-c-d-e-f-g-h-i-j--
----j-i-h-g-f-e-d-c-d-e-f-g-h-i-j----
------j-i-h-g-f-e-d-e-f-g-h-i-j------
--------j-i-h-g-f-e-f-g-h-i-j--------
----------j-i-h-g-f-g-h-i-j----------
------------j-i-h-g-h-i-j------------
--------------j-i-h-i-j--------------
----------------j-i-j----------------
------------------j------------------
```

The center of the rangoli has the first alphabet letter a, and the boundary has the $N^{th}$alphabet letter (in alphabetical order).
"""

n = 20
l = 'abcdefghijklmnopqrstuvwxyz'

for i in range(0,n-1):
    a = '-'.join([str(l[(i-1)%26]) for i in range(n,n-i-1,-1)])
    print('-'*((n-(i+1))*2)+a+a[-2::-1]+'-'*((n-(i+1))*2))


for i in range(n-1,-1,-1):

    a = '-'.join([str(l[(i-1)%26]) for i in range(n,n-i-1,-1)])
    print('-'*((n-(i+1))*2)+a+a[-2::-1]+'-'*((n-(i+1))*2))

"""### `Problem-6:` Compress a string!

You are given a string $S$. Suppose a character '$c$' occurs consecutively $X$ times in the string. Replace these consecutive occurrences of the character '$c$' with $$(X, c) in the string. For a better understanding of the problem, check the explanation.

**Input Format:**

A single line of input consisting of the string $S$.

**Output Format:**

A single line of output consisting of the modified string.

**Sample Input:**

```bash
1222311
```

**Sample Output:**

```bash
(1, 1) (3, 2) (1, 3) (2, 1)
```

**Explanation:**

First, the character occurs only once. It is replaced by (1, 1). Then the character 2 occurs three times, and it is replaced by (3, 2 )and so on. Also, note the single space within each compression and between the compressions.
"""

def recursive_count(arr):

    if len(arr) == 0:
        return ""

    index = 0
    while index < (len(arr)-1) and arr[index] == arr[index+1]:
        index+=1

    ans = (index+1,arr[index])

    return str(ans) + " " + str(recursive_count(arr[index+1:]))


print(recursive_count([1,2,2,2,3,1,1]))

"""### `Problem-7:` Word order

You are given words. Some words may repeat. For each word, output its number of occurrences. The output order should correspond with the input order of appearance of the word. See the sample input/output for clarification.

*Note: Each input line ends with a **"\n"** character.*

**Input Format:**

The first line contains the integer, $n$.

The next $n$ lines each contain a word.

**Output Format:**

Output $2$ lines.

On the first line, output the number of distinct words from the input.

On the second line, output the number of occurrences for each distinct word according to their appearance in the input.

**Sample Input:**

```bash
4
bcdef
abcdefg
bcde
bcdef
```

**Sample output:**

```bash
3
2 1 1
```

**Explanation:**

There are $3$ distinct words. Here, "bcdef" appears twice in the input at the first and last positions. The other words appear once each. The order of the first appearances are "bcdef", "abcdefg" and "bcde" which corresponds to the output.
"""

d = {}
n = int(input("Enter number: "))
for i in range(n):
  word = input("Enter word: ")
  if word in d:
    d[word]+=1
  else:
    d[word]=1
print(len(d))
for i in d:
    print(d[i],end=' ')

"""### `Problem-8:`Iterables & Iterators

You are given a list of $N$ lowercase English letters. For a given integer $K$, you can select any $K$ indices (assume 1-based indexing) with a uniform probability from the list. Find the probability that at least one of the $K$ indices selected will contain the letter '$a$'.

**Input Format:**

The input consists of three lines. The first line contains the integer $N$, enoting the length of the list. The next line consists of &N& space-separated lowercase English letters, denoting the elements of the list.

The third and the last line of input contains the integer $K$, denoting the number of indices to be selected.

**Output Format:**

Output a single line consisting of the probability that at least one of the $K$ indices selected contains the letter '$a$'.

Note: The answer must be correct up to 3 decimal places.

**Sample Input:**

```bash
4
a a c d
2
```

**Sample Output:**

```bash
0.8333
```

**Explanation:**

All possible unordered tuples of length 2 comprising of indices from 1 to 4 are:
(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)

Out of these 6 combinations, 5 of them contain either index 1 or index 2 which are the indices that contain the letter '$a$'. Hence, the answer is $\frac{5}{6}$
"""

from itertools import combinations
count=0
total=0
n = int(input("Enter length of list: "))
l = input("Enter list: ").split()
k = int(input("Enter size of tuple: "))

ans = list(combinations(l,k))
for i in ans:
  if 'a' in i:
    count+=1
    total+=1
  else:
    total+=1
print(f"{(count/total):.4f}")

"""### `Problem-9:` The Captain's Room

Mr. Anant Asankhya is the manager at the INFINITE hotel. The hotel has an infinite amount of rooms.

One fine day, a finite number of tourists come to stay at the hotel.
The tourists consist of:

→ A Captain.

→ An unknown group of families consisting of $K$ members per group where $K ≠ 1$

The Captain was given a separate room, and the rest were given one room per group.

Mr. Anant has an unordered list of randomly arranged room entries. The list consists of the room numbers for all of the tourists. The room numbers will appear $K$ times per group except for the Captain's room.

Mr. Anant needs you to help him find the Captain's room number.
The total number of tourists or the total number of groups of families is not known to you. You only know the value of $K$ and the room number list.

**Input Format:**

The first line consists of an integer, $K$, the size of each group.

The second line contains the unordered elements of the room number list.

**Output Format:**

Output the Captain's room number.

**Sample Input:**
```bash
5
1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2
```

**Sample Output**
```bash
8
```

**Explanation:**

The list of room numbers contains 31 elements. Since K is 5, there must be groups 6 of families. In the given list, all of the numbers repeat 5 times except for room number 8.
Hence, 8 is the Captain's room number.
"""

k = int(input("Enter number of families: "))
rooms =input("Enter room numbers: ").split()
ans = {}
for i in rooms:
  if i in ans:
    ans[i]+=1
  else:
    ans[i]=1
print(min(ans.items(), key=lambda x: x[1])[0])

"""### `Problem-10:` Classes: Dealing with Complex Numbers

For this challenge, you are given two complex numbers, and you have to print the result of their addition, subtraction, multiplication, division and modulus operations.

The real and imaginary precision part should be correct up to two decimal places.

**Input Format:**

One line of input: The real and imaginary part of a number separated by a space.

**Output Format:**

For two complex numbers $C$ and $D$, the output should be in the following sequence on separate lines:

- $C + D
- $C - D
- $C * D$
- $C / D$
- $mod(C)$
- $mod(D)$

For complex numbers with non-zero real ($A$) and complex part ($B), the output should be in the following format:

$A + Bi$

Replace the plus symbol ($+$) with a minus symbol ($-$) when $B<0$.

For complex numbers with a zero complex part i.e. real numbers, the output should be:

$A + 0.00i$

For complex numbers where the real part is zero and the complex part ($B$) is non-zero, the output should be:

$0.00 + Bi$

**Sample Input:**

```bash
2 1     a b
5 6     c d
```

**Sample Output:**

```bash
7.00+7.00i
-3.00-5.00i
4.00+17.00i
0.26-0.11i
2.24+0.00i
7.81+0.00i
```

**Concept:**

Solve this problem using Object Oriented way. Methods with a double underscore before and after their name are considered as built-in methods. They are used by interpreters and are generally used in the implementation of overloaded operators or other built-in functionality.

```bash
__add__-> Can be overloaded for + operation

__sub__ -> Can be overloaded for - operation

__mul__ -> Can be overloaded for * operation
```
"""

import math

class ComplexNumbers:

  def __init__(self,real,complex):
    self.real = real
    self.complex = complex

  def __add__(self,others):
    if (+self.complex+others.complex) > 0:
      return f"{(self.real+others.real):.2f}+{(+self.complex+others.complex):.2f}i"
    else:
      return f"{(self.real+others.real):.2f}{(+self.complex+others.complex):.2f}i"

  def __sub__(self,others):
    if self.complex-others.complex < 0:
      return f"{(self.real-others.real):.2f}{(self.complex-others.complex):.2f}i"
    else:
      return f"{(self.real-others.real):.2f}+{(self.complex-others.complex):.2f}i"

  def __mul__(self,others):
    if ((math.prod((self.real,others.complex))+math.prod((self.complex,others.real)))) > 0:
      return f"{(math.prod((self.real,others.real))-math.prod((self.complex,others.complex))):.2f}+{(math.prod((self.real,others.complex))+math.prod((self.complex,others.real))):.2f}i"
    else:
      return f"{(math.prod((self.real,others.real))-math.prod((self.complex,others.complex))):.2f}{(math.prod((self.real,others.complex))+math.prod((self.complex,others.real))):.2f}i"

  def __truediv__(self,others):
    if ((((math.prod((self.real,-others.complex))+math.prod((self.complex,others.real))))/(others.real**2+others.complex**2))) < 0:
      return f"{(((math.prod((self.real,others.real))-math.prod((self.complex,-others.complex))))/(others.real**2 + others.complex**2)):.2f}{(((math.prod((self.real,-others.complex))+math.prod((self.complex,others.real))))/(others.real**2+others.complex**2)):.2f}i"
    else:
      return f"{(((math.prod((self.real,others.real))-math.prod((self.complex,-others.complex))))/(others.real**2 + others.complex**2)):.2f}+{(((math.prod((self.real,-others.complex))+math.prod((self.complex,others.real))))/(others.real**2+others.complex**2)):.2f}i"


  def mod(self):
    return f"{math.sqrt(self.real**2+self.complex**2):.2f}+{0.00}i"

n1 = ComplexNumbers(2,1)
n2 = ComplexNumbers(5,6)

print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1/n2)
print(n1.mod())
print(n2.mod())

"""### `Problem-11:` Find the Torsional angle

You are given four points $A, B, C$ and $D$ in a 3-dimensional Carterian coordinate system. You are required to print the angle between the plane made by the points $A, B, C$ and $B, C, D$ in degrees (**not radians**). Let the angle be $\phi$.

$cos(\phi) = (X.Y)/|X||Y|$ where $X = AB * BC$ and $Y = BC * CD$

Here, $X.Y$ means the dot product of $X$ and $Y$ and $AB*BC$ means the cross product of vectors $AB$ and $BC$. Also, $AB = B - A$

**Input Format:**

One line of input containing the space separated floating number values of the $X, Y$ and $Z$ coordinates of a point.

**Output Format:**

Output the angle correct up to two decimal places.

**Sample Input:**

```bash
0 4 5
1 7 6
0 5 9
1 7 2
```

**Sample Output:**

```bash
8.19
```
"""

import math


class Angle:
  def __init__(self,x,y,z):
    self.x = x
    self.y = y
    self.z = z

  def __sub__(self,others):
    return Angle(self.x-others.x,self.y-others.y,self.z-others.z)

  def cross(self, other):
      return Angle( self.y * other.z - self.z * other.y,
                   self.z * other.x - self.x * other.z,
                   self.x * other.y - self.y * other.x)


  def dot(self,other):
    return (self.x*other.x + self.y*other.y + self.z*other.z)



  def modulus(self):
    return math.sqrt(self.x**2 + self.y**2 + self.z**2)




a = Angle(0,4,5)
b = Angle(1,7,6)
c = Angle(0,5,9)
d = Angle(1,7,2)
X = (b-a).cross(c-b)
print(X)
Y = (c-b).cross(d-c)
print(Y)
ans = math.degrees(math.acos(X.dot(Y)/(X.modulus() * Y.modulus())))
print(ans)

"""### `Problem-12:` Maximize it

You are given a function $f(X) = X^2$. You are also given $K$ lists. The $i^{th}$ list consists of $N_i$ elements. You have to pick one element from each list so that the value from the equation below is maximized:

$S = (f(X_1) + f(X_2) + ... + f(N_k)) \% M $

$X_i$ denotes the element picked from the $i^{th}$ list. Find the maximized value $S_{max}$ obtained.

$\%$ denotes the modulo operator.

Note that you need to take exactly one element from each list, not necessarily the largest element. You add the squares of the chosen elements and perform the modulo operation. The maximum value that you can obtain, will be the answer to the problem.

**Input Format:**

The first line contains 2 space separated integers $K$ and $M$.

The next $K$ lines each contains an integer $N_i$, denoting the number of elements in the $i^{th}$ list, followed by $N_i$ space separated integers denoting the elements in the list.

**Output Format:**

Output a single integer denoting the value $S_max$

**Sample Input:**

```bash
3 1000
2 5 4
3 7 8 9
5 5 7 8 9 10
```

**Sample Output:**

```bash
206
```

**Explanation:**

Picking 5 from $1^{st}$ list, 9 from the $2^{nd}$ list and 10 from the $3^{rd}$ list gives the maximum $S$ value equal to $(5^2 + 9^2 + 10^2)\%1000 = 206$
"""

from itertools import product
k = int(input("Enter number of list: "))
m = int(input("Enter the modulo number: "))
data = []
maximum_sum = 0
for i in range(k):
  l = list(map(int,input("Enter list:  ").split()))
  data.append(sorted(l))

for i in product(*data,repeat=1):
  square_sum=0
  for j in i:
    square_sum+=(j**2)
  if (maximum_sum%m) < (square_sum%m):
    maximum_sum = square_sum

print(maximum_sum%m)

"""### `Problem-13:` Diamond shape

Write a python program to print the diamond shape. Given a number n, write a program to print a diamond shape with 2n rows.

![Sample](https://media.geeksforgeeks.org/wp-content/cdn-uploads/diamond.png)
"""

n = int(input("Enter size: "))
for i in range(1,n+1):
  print(" "*(n-i)+"* "*i)
for i in range(n,0,-1):
  print(" "*(n-i)+"* "*i)

"""### `Problem-14:` Write a python function to print the half-diamond star pattern.

Given an integer N, the task is to print half-diamond-star pattern.

```bash
*
**
***
****
*****
******
*****
****
***
**
*
```
"""

n = int(input("Enter size: "))

for i in range(1,n):
  print("*"*i)

for i in range(n,0,-1):
  print("*"*i)

"""### `Problem-15:` Write a Python program to find the power of a given number using recursion.

Given a number $N$ and power $P$, the task is to find the power of a number ( i.e. $N^P$ ) using recursion.
"""

def recursive_power(n,p):
  if p==0:
    return 1
  else:
    return n * recursive_power(n,p-1)
n,p = tuple(map(int,input("Enter number and its power: ").split()))
print(recursive_power(n,p))

"""### `Problem-16:` Largest number in a list

Write a Python program to find the largest number in a list without using built-in methods.
"""

l = list(map(int,input("Enter a list of numbers: ").split()))
maxi=0
for i in l:
  if maxi < i:
    maxi = i

print(maxi)

"""### `Problem-17:` Reverse integer

Write a python function that accepts any length of the integers and prints that integer in a reverse manner. Don't use any python trick or python special syntax.
"""

def recurive_reverse(n):
  if n<10:
    return str(n)
  else:
    return str(n%10)+str(recurive_reverse(n//10))
n = int(input("Enter numbers of any length: "))

print(recurive_reverse(n))

"""### `Problem-18:` Celsius to Farenhight

Write a Python function that can convert the degree of Celsius to the Farenhight scale.


"""

def celcius_fahrenheit(n):
  return f"{(((9/5) * n)+32):.2f}"

Celcius = celcius = int(input("Enter temperature(C): "))
print(f"The temperature in fahrenheit: {celcius_fahrenheit(celcius)}")

"""### `Problem-19:` is it right?

You are given two values $a$ and $b$. Perform integer division and print $a/b$.

**Input Format:**

The first line contains $T$, the number of test cases.

The next $T$ lines each contain the space separated values of $a$ and $b$.

**Output Format:**

Print the value of $a/b$.

In the case of *ZeroDivisionError* or *ValueError*, print the error code.

**Sample Input:**

```bash
3
1 0
2 5
3 1
```

**Sample Output:**

```bash
Error Code: integer division or modulo by zero
Error Code: invalid literal for int() with base 10: '$'
3
```
"""

n = int(input("Enter range: "))
for i in range(n):
  try:
    x,y = tuple(map(int,input("Enter 2 numbers: ").split()))
  except ValueError as e:
    print(f"Error Code: {e}")
    continue
  try:
    a = x//y
  except ZeroDivisionError:
    print("Error Code: integer division or modulo by zero")
    continue

  else:
    print(a)

"""### `Problem 20:` Piling Up!

There is a horizontal row of $n$ cubes. The length of each cube is given. You need to create a new vertical pile of cubes. The new pile should follow these directions: if $cube[i]$ is on top of $sube[j]$ then $sideLength[j] >= sigeLength[i]$.

When stacling the cubes, you can only pick up either leftmost or the rightmost cube each time. Print Yes if it possible to stack the cubes. Otherwise, print No.

**Example:**

$blocks = [1, 2, 3, 8, 7]$

Result: No

After choosing the rightmost element 7, choose the leftmost element, 1. After than, the choices are 2 and 8. These are both larger than the top block of size 1.

$blocks = [1, 2, 3, 7, 8]$

Result: Yes

Choose blocks from right to left in order to successfully stack the blocks.

**Input Format:**

The first line contains a single integer $T$, the number of test cases.

For each test case, there are 2 lines.

The first line of each test case contains $n$, the number of cubes.

The second line contains $n$ space separated integers, denoting the sideLengths of each cube in that order.

**Output Format:**

For each test case, output a single line containing either `Yes` or `No`.

**Sample Input:**

```bash
STDIN        Function
-----        --------
2            T = 2
6            blocks[] size n = 6
4 3 2 1 3 4  blocks = [4, 3, 2, 1, 3, 4]
3            blocks[] size n = 3
1 3 2        blocks = [1, 3, 2]
```

**Sample Output:**

```bash
Yes
No
```

**Explanation:**

In the first test case, pick in this order: *left-4, right-4, left-3, right-3,left-2, right-1*

In the second test case, no order gives an appropriate arrangement of vertical cubes. 3 will always come after either 1 or 2.
"""

iterations = int(input(""))
for i in range(iterations):
    n = int(input(""))
    arr = list(map(int,input("").split()))
    flag = True


    maxi = float('inf')
    while len(arr)>=1:
      if  arr[0]>=arr[-1] and arr[0]<= maxi:
        maxi=arr[0]
        arr=arr[1:]


      elif arr[-1] > arr[0] and  arr[-1] <= maxi:
        maxi =arr[-1]
        arr=arr[:-1]


      else:
        flag = False
        break

    if flag:
      print("Yes")
    else:
      print("No")

"""### `Problem 21` The following Python code represents a Tic-Tac-Toe board as a list of
lists:
`[ [ '#' , 'o' , 'x' ] , [ '#' , '#' , 'o' ] , [ 'x' , '#' , 'o' ] ]`

The `#` symbols represent blank squares on the board. Write a function
print_board that takes a list of lists as an argument and prints out a
Tic-Tac-Toe board in the following format:
```
   | o | x
------------
   |   | o
------------
 x |   | o
```
"""

def print_board(arr):
  text = ''
  for i in arr:
    for j in range(len(i)):
      if i[j] == '#':
        text+=' '+' | '
      elif j == 2:
        text+=str(i[j])+'\n'+'----------'+'\n'
      elif i[j] != '#':
        text+= str(i[j]) +' | '

  return text


print(print_board([ [ '#' , 'o' , 'x' ] , [ '#' , '#' , 'o' ] , [ 'x' , '#' , 'o' ] ]))

"""### `Problem 22:` Wobbly Number
A “wobbly” number is one in which the digits alternate between being higher and lower than the preceding one. Here are some wobbly numbers: `19284756242, 90909, 0909`. Write a function that accepts a list of digits to be checked for wobbliness. If the sequence of digits is wobbly, the function should return True, otherwise False.

"""

def wobbly_no(number):
  data = str(number)
  ans=[]
  for i in range(len(data)):
    if i < (len(data)-2):
      if data[i] < data[i+1] > data[i+2]:
        ans.append(data[i])

      elif data[i] > data[i+1] < data[i+2]:
        ans.append(data[i])
  return ans


b = str(12323)
a = wobbly_no(b)
print(len(a) == (len(b)-2))

"""### `Problem 23-25`
Imagine a fictional land where monetary units aren’t based on decimal orders. In this land, we have 3 basic units of currency:

* The Blink. The smallest unit of currency.
* The Hoojim. Worth 12 Blinks.
* The Bung. Worth 20 Hooja (plural of Hoojim) or 240 Blinks.

####`Problem-23` Write a function called `deBung`
Write a function called deBung that accepts an integer representing a number of Bungs and displays the number of Hooja and Blink it is worth.

For example,calling the function like this:

```
deBung ( 4 )
```
Will produce the following output:
`4 Bungs is worth 80 Hoojim or 960 Blinks.`
"""

def debung(n):
  return f"{n} Bungs is worth {n*20} Hoojim or {n*240} Blinks"

print(debung(4))

"""####`Problem-24` Write a function called `enBlinkHoojaBung`
Write a function called enBlinkHoojaBung that takes a number of Blinks and outputs its equivalent in Blink, Hooja and Bung, using the smallest number of coins. Coins in our imaginary land are made of a very heavy metal, so this is important.

If the function is called with the value `506`, the output should be:
`506 Blinks is worth 2 Bung, 1 Hoojim and 6 Blinks`.
"""

def debung(n):
  bung = n//240
  hoojim = (n-(bung*240))//12
  blinks = (n - (bung*240) - (hoojim*12))
  return f"{n} Blinks is worth {bung} Bung ,{hoojim} Hoojim and {blinks} Blinks"

print(debung(506))

"""####`Problem-25` Rewrite `enBlinkHoojaBung`
Rewrite enBlinkHoojaBung so that it returns a tuple of Blinks, Hooja and Bung values instead of writing to the screen.
The last example would return `( 2 , 1 , 6 )`.

"""

def debung(n):
  bung = n//240
  hoojim = (n-(bung*240))//12
  blinks = (n - (bung*240) - (hoojim*12))
  return (bung,hoojim,blinks)

print(debung(506))

"""###`Problem 26-28` Convert the following iterative functions into recursive functions:

P-26:

```
def sum_even ( n : int) :
    total = 0
    for i in range ( 2 , n + 1 , 2 ) :
        total += i
    return total
```
P-27:
```
def min ( l:list ) :
    m = 0
    for i in l :
        if i<m :
            m = i
    return m
```
P-28:
```
def prod ( l : list ) :
    product , i = 1 , 0
    while i < len ( l ) :
        product *= l[i]
        i += 1
    return product
```
"""

def sum_even(n):
  if n==0:
    return 0
  else:
    return n + sum_even(n-2)

print(sum_even(20))

def min(l):
  if len(l)==1:
    return l[0]
  else:
    if l[-1] < l[-2] and l[-1] < l[0]:
      l[0] = l[-1]
    elif l[-1] > l[-2] and l[-2] < l[0]:
      l[0]=l[-2]
    return min(l[:-1])

print(min([5, 4, 3, 2, 1, 0, 6, 7, 8, 9]))

def prod(l):
  if len(l)==0:
    return 1
  else:
    return l[0] * prod(l[1:])

print(prod([1,2,3]))

"""###`Problem 29-31` Convert the following iterative functions into recursive functions:
P-29:
```
def sum_odd ( n , total ) :
    if n == 1 :
        return total
    elif n % 2 == 0 :
        return sum_odd ( n - 1 , total )
    else :
        return sum_odd ( n - 2 , total + n )


```
P-30:
```
def max ( l , n ) :
    if l == [ ] :
        return n
    elif l[0] > n :
        return max ( l[1:] , l[0] )
    else :
        return max ( l[1:] , n )

```
P-31:
```
def mylen ( l , n ) :
    if l == [] :
        return n
    else :
        return mylen ( l[1:] , n +1 )
```
"""

def sum_odd(n,total):
  for i in range(1,n):
    if n==1:
      return total

    elif n%2==0:
      n-=1

    elif n%2!=0:
      total+=n
      n-=2
      i+=1
  return total

print(sum_odd(4,20))

def max(l,n):
  max = 0
  for i in range(n):
    if max < l[i]:
      max=l[i]
  return max

print(max([2,9,0,1,4],5))

def mylen(l,n):
  for i in l:
    n+=1
  return n

print(mylen([1,2,3],3))

"""###`Problem 32-35
P-32:
> Use map and lambda to turn a list of integers from `1 to 100` into a list of even numbers from `2 to 200`.

P-33:
> Use filter to generate a list of odd numbers from 0 to 100

P-34:
> Use a list comprehension to generate a list of odd numbers from 0 to
100.

P-35:

> Write a generator function (using the yield keyword) that generates
factorial numbers.

"""

d = []
for i in range(1,101):
  d.append(i)

e = list(map(lambda x:x*2 ,d))
print(e)

d = []
for i in range(0,100):
  d.append(i)

e = list(filter(lambda x:x%2!=0 ,d))
print(e)

d = []
for i in range(0,100):
  d.append(i)

e = [j for i in d for j in list(filter(lambda x:x%2!=0 ,d[i:i+1]))]
print(e)

def generator(n=0):
  mul=1
  times = 1
  while True:
    mul*=times
    yield mul
    times+=1


gen = generator()

for i in range(5):
  print(next(gen))

"""###`Problem-36:` Ackermann’s Function
Ackermann’s Function is defined as:
```
          n+1 if m = 0
 A(m,n) = A(m−1,1) if m > 0 and n = 0
          A(m−1,A(m,n−1)) if m > 0 and n > 0
```

i. Write a recursive Python function to implement Ackermann’s Function.

ii. How many recursive calls will be required to evaluate A(2,3)?
"""

def ackermanns_function(m,n,i,count):
  if m==0:
    i+=1
    count(i)
    return n+1
  elif m>0 and n==0:
    i+=1
    count(i)
    return ackermanns_function(m-1,1,i,count)
  elif m>0 and n>0:
    i+=1
    count(i)
    return ackermanns_function(m-1,ackermanns_function(m,n-1,i,count),i,count)

def count(count=0):
  print(f"This code executed {count} times")


print(ackermanns_function(2,3,0,count))

"""###`Problem-37:` Palindrome String
Write a recursive function implementation of `isPalindrome` to test whether or
not a string is a palindrome.

`a man, a plan, a canal, panama!` is a palindrome – so we do not make spaces and special characters(! here) significant.
"""

def is_pailindrome(string):
  string = ''.join([i.lower() for i in string if i.isalpha()])
  if len(string)<=1:
    return 1
  elif string[0] == string[-1]:
    return  is_pailindrome(string[1:-1])
  else:
    return 0


print(is_pailindrome('a man, a plan, a canal, panama!')==1)

"""###`Problem-38` Create a module for playing Tic-Tac-Toe.
Hint: You may want to consider the following functions:
1. print_board ( ) – from the programming exercise above, except that you will want to use a global board variable, rather than a function argument.
2. has_won ( ) – check to see whether either player has won. This function should return the string ’o’ or ’x’ if either the o or x player has won and ’#’ if neither player has won. A player wins in Tic-Tac-Toe if they have three of their counters in a row, a column or a diagonal.
3. place_counter ( sq , counter ) – place the counter on a particular square of the board. The first argument should be a number between 0 and 8 and the second argument should be either ’o’ or ’x’. You should consider the squares on the
board to be numbered as in the diagram below.
```
    0 | 1 | 2
    ----------
    3 | 4 | 5
    ----------
    6 | 7 | 8
```
Using a numbering such as this one makes the answer to
this challenge simpler!

4. next_play ( ) – This function should ask the user for the next move they want to play. You should make sure that the user knows whether x or o is currently playing. You can assume that the user will enter an integer value. You should still check that the integer the player has provided is between 0 and 8 inclusive.
"""

def print_board(arr):
  text = ''
  for i in arr:
    for j in range(len(i)):
      if i[j] == '#':
        text+=' '+' | '
      elif j == 2:
        text+=str(i[j])+'\n'+'----------'+'\n'
      elif i[j] != '#':
        text+= str(i[j]) +' | '

  return text

l = [[0,1,2],[3,4,5],[6,7,8]]

def has_won(data):
  data = set(data)
  # if set((0,3,6)).issubset(data) or set((0,4,8)).issubset(data) or set((0,1,2)).issubset(data) or set((1,4,7)).issubset(data) or set((2,5,8)).issubset(data) or set((6,7,8)).issubset(data) or set((2,4,6)).issubset(data) or set((3,4,5)).issubset(data):
  if data.issuperset({0,3,6}) or data.issuperset({0,4,8}) or data.issuperset({0,1,2}) or data.issuperset({1,4,7}) or data.issuperset({2,5,8}) or data.issuperset({6,7,8}) or data.issuperset({2,4,6}) or data.issuperset({3,4,5}):
    return True
  else:
    return False


def place_counter(data:list,point):
  data.append(point)


def next_play(i):
  if i%2==0:
    return 0
  else:
    return 1

data_player_1 = []
data_player_2 = []
i = 0
while i<=8:

  if has_won(data_player_1) == True:
    break

  if has_won(data_player_2) == True:
    break


  player_turn = next_play(i)

  play = int(input(f"Player {next_play(i)+1} Turn \nEnter the index of board where you want to play:  "))

  if 0<=play<=8 and play not in data_player_1 and play not in data_player_2:

    if player_turn==0:

      place_counter(data_player_1,play)
      for k in l:
        for j in range(len(k)):
          if k[j]==play:
            k[j]='O'

    elif player_turn == 1:
      place_counter(data_player_2,play)
      for k in l:
        for j in range(len(k)):
          if k[j]==play:
            k[j]='X'

  else:
    while True:
        plays = int(input("Enter Valid Nuber: "))
        if 0<=plays<=8 and plays not in data_player_1 and plays not in data_player_2:
          if player_turn==0:

            place_counter(data_player_1,plays)
            break

          elif player_turn == 1:
            place_counter(data_player_2,plays)
            break


  i+=1


if has_won(data_player_2):
  print("Player 2 winner")
else:
  print("Player 1 winner")

print(print_board(l))

"""###`Problem 39:` Die class
Create a class to represent a single die that can have any positive integer number of sides. This kind of die might be used when playing role-playing games (RPGs).

"""

import random
class Die:
  def __init__(self,number):
    self.range = number
    self.current = None


  def roll(self):
    value = random.randint(1,self.range)
    self.current = value
    return self.current

  def __str__(self):
    return f"{self.current}"





die = Die(6)
print(die)
print(die.roll())

"""###`Problem -40` Account class
Write a class `Account` that stores the `current balance`, `interest rate` and `account number` of a bank account. Your class should provide methods to `withdraw`, `deposit` and `add interest` to the account. The user should only be allowed to withdraw money up to some `overdraft limit`. If an account goes overdrawn, there is `fee charged`.
"""

class Account:
  def __init__(self):
    self.balance = None
    self.interest = None
    self.accountno = None

  def current_balance(self,balance):
    self.balance = balance

  def interest_rate(self,interest):
    self.interest = interest

  def account_no(self,number):
    self.account_no = number

  def withdraw(self,number):
    if number <= 10000:
      self.balance-=number
    else:
      print("Withdraw limit crossed fee would be deducted")
      self.balance-=(number+500)

  def deposit(self,number):
    self.balance+=number


  def add_interest(self):
    self.balance+=(self.balance*(self.interest/100))


account = Account()
account.current_balance(20000)

account.interest_rate(5)

account.withdraw(5000)

account.deposit(1000)

account.add_interest()

print(account.balance)